'\" t
.\"     Title: pgpainless-cli-generate-completion
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"    Manual: PGPainless-CLI Manual
.\"    Source: generate-completion 4.6.3
.\"  Language: English
.\"
.TH "PGPAINLESS\-CLI\-GENERATE\-COMPLETION" "1" "" "generate\-completion 4.6.3" "PGPainless\-CLI Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pgpainless\-cli\-generate\-completion \- Stateless OpenPGP Protocol
.SH "SYNOPSIS"
.sp
\fBpgpainless\-cli generate\-completion\fP [\fB\-hV\fP] [\fB\-\-debug\fP]
.SH "DESCRIPTION"
.sp
Generate bash/zsh completion script for pgpainless\-cli.
Run the following command to give \f(CRpgpainless\-cli\fP TAB completion in the current shell:
.sp
.if n .RS 4
.nf
source <(pgpainless\-cli generate\-completion)
.fi
.if n .RE
.SH "OPTIONS"
.sp
\fB\-\-debug, \-\-stacktrace\fP
.RS 4
Print stacktrace
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information and exit.
.RE
.SH "EXIT CODES:"
.sp
\fB0\fP
.RS 4
Successful program execution
.RE
.sp
\fB1\fP
.RS 4
Generic program error
.RE
.sp
\fB3\fP
.RS 4
Verification requested but no verifiable signature found
.RE
.sp
\fB13\fP
.RS 4
Unsupported asymmetric algorithm
.RE
.sp
\fB17\fP
.RS 4
Certificate is not encryption capable
.RE
.sp
\fB19\fP
.RS 4
Usage error: Missing argument
.RE
.sp
\fB23\fP
.RS 4
Incomplete verification instructions
.RE
.sp
\fB29\fP
.RS 4
Unable to decrypt
.RE
.sp
\fB31\fP
.RS 4
Password is not human\-readable
.RE
.sp
\fB37\fP
.RS 4
Unsupported Option
.RE
.sp
\fB41\fP
.RS 4
Invalid data or data of wrong type encountered
.RE
.sp
\fB53\fP
.RS 4
Non\-text input received where text was expected
.RE
.sp
\fB59\fP
.RS 4
Output file already exists
.RE
.sp
\fB61\fP
.RS 4
Input file does not exist
.RE
.sp
\fB67\fP
.RS 4
Cannot unlock password protected secret key
.RE
.sp
\fB69\fP
.RS 4
Unsupported subcommand
.RE
.sp
\fB71\fP
.RS 4
Unsupported special prefix (e.g. "@ENV/@FD") of indirect parameter
.RE
.sp
\fB73\fP
.RS 4
Ambiguous input (a filename matching the designator already exists)
.RE
.sp
\fB79\fP
.RS 4
Key is not signing capable
.RE
.sp
\fB83\fP
.RS 4
Options were supplied that are incompatible with each other
.RE
.sp
\fB89\fP
.RS 4
The requested profile is unsupported, or the indicated subcommand does not accept profiles
.RE
.sp
\fB97\fP
.RS 4
The implementation supports some form of hardware\-backed secret keys, but could not identify the hardware device
.RE
.sp
\fB101\fP
.RS 4
The implementation tried to use a hardware\-backed secret key, but the cryptographic hardware refused the operation for some reason other than a bad PIN or password
.RE
.sp
\fB103\fP
.RS 4
The primary key of a KEYS object is too weak or revoked
.RE
.sp
\fB107\fP
.RS 4
The CERTS object has no matching User ID
.RE